# Generated by Django 4.2.11 on 2025-05-07 11:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('guest_count', models.IntegerField()),
                ('resevatation_date', models.DateField(auto_now=True)),
                ('comments', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='price',
            field=models.IntegerField(default = 0),
            preserve_default=False,
        ),
    ]
